import type { Tool } from "@/lib/tools";

// Brazilian Portuguese tool prose (machine-translated, pending human
// spot-check). Pilot set of the highest-opportunity tools for BR search;
// any tool not listed here falls back to English via the resolver. Only
// translatable fields are overridden — slug/category/status/flags stay
// structural.
export const PT_TOOLS: Record<string, Partial<Tool>> = {
  "compress-pdf": {
    name: "Comprimir PDF",
    description: "Diminua o tamanho de um PDF grátis, direto no navegador. Reduza para enviar por e-mail ou anexar em formulários — sem upload, sem cadastro.",
    keywords: ["comprimir pdf", "diminuir pdf", "reduzir tamanho do pdf", "compactar pdf", "comprimir pdf gratis"],
    answer: "Para comprimir um PDF, carregue o arquivo aqui, escolha a qualidade e baixe a versão menor. As páginas são reprocessadas localmente no seu navegador — o documento nunca é enviado a um servidor, então é seguro até para contratos e extratos.",
    intro: "Comprimir PDF reduz o tamanho do arquivo reprocessando as páginas com qualidade ajustável — ideal para anexar em e-mails e formulários com limite de tamanho. Tudo acontece no seu navegador: o PDF nunca sai do seu dispositivo.",
    steps: ["Escolha um arquivo PDF.", "Ajuste a qualidade (ou use uma predefinição de tamanho).", "Baixe o PDF comprimido."],
    faqs: [
      { q: "Meu PDF é enviado a um servidor?", a: "Não. A compressão acontece inteiramente no seu navegador — o documento nunca sai do seu dispositivo." },
      { q: "Quanto o arquivo diminui?", a: "PDFs escaneados ou cheios de imagens costumam reduzir de 70% a 90%. PDFs só de texto já são pequenos e reduzem menos." },
      { q: "O texto continua selecionável?", a: "Nas predefinições de tamanho as páginas são convertidas em imagem para atingir o alvo, então o texto deixa de ser selecionável. Guarde o original se precisar dele." },
    ],
  },
  "merge-pdf": {
    name: "Juntar PDF",
    description: "Junte vários PDFs em um único arquivo, grátis e no seu navegador. Arraste para ordenar e baixe — sem upload, sem marca d'água.",
    keywords: ["juntar pdf", "unir pdf", "combinar pdf", "mesclar pdf", "juntar pdf gratis"],
    answer: "Para juntar PDFs, selecione os arquivos, arraste para colocar na ordem certa e clique em juntar. O arquivo combinado é gerado localmente no seu navegador — nada é enviado a servidor algum.",
    intro: "Juntar PDF combina dois ou mais PDFs em um único documento, na ordem que você escolher. Funciona inteiramente no seu navegador, sem upload e sem marca d'água.",
    steps: ["Selecione dois ou mais PDFs.", "Arraste para definir a ordem.", "Clique em juntar e baixe o arquivo único."],
    faqs: [
      { q: "Meus arquivos são enviados?", a: "Não — a junção acontece localmente no navegador; seus documentos nunca saem do dispositivo." },
      { q: "Existe limite de arquivos?", a: "Não há limite artificial — apenas a memória do seu dispositivo." },
      { q: "É grátis mesmo?", a: "Sim: grátis, sem cadastro e sem marca d'água." },
    ],
  },
  "split-pdf": {
    name: "Dividir PDF",
    description: "Extraia páginas de um PDF ou divida-o em partes, grátis e no navegador. Escolha as páginas e baixe — sem upload.",
    keywords: ["dividir pdf", "separar pdf", "extrair paginas do pdf", "separar paginas pdf"],
    answer: "Para dividir um PDF, carregue o arquivo, marque as páginas (ou intervalos) que quer extrair e baixe o resultado. Tudo roda no seu navegador — o documento não é enviado.",
    intro: "Dividir PDF extrai páginas específicas ou separa um documento em partes menores. Escolha páginas soltas ou intervalos e baixe na hora — tudo localmente, sem upload.",
    steps: ["Escolha um PDF.", "Selecione as páginas ou intervalos que deseja extrair.", "Baixe o novo PDF com as páginas escolhidas."],
    faqs: [
      { q: "O documento é enviado?", a: "Não — a divisão acontece no seu navegador; o arquivo nunca sai do seu dispositivo." },
      { q: "Posso extrair só uma página?", a: "Sim — selecione apenas a página desejada e baixe um PDF só com ela." },
    ],
  },
  "sign-pdf": {
    name: "Preencher e assinar PDF",
    description: "Preencha e assine um PDF online grátis: digite nos campos, desenhe ou envie sua assinatura, posicione e baixe. Sem upload, sem cadastro.",
    keywords: ["assinar pdf", "assinatura digital pdf", "preencher e assinar pdf", "assinar pdf gratis", "como assinar pdf", "assinar documento online"],
    answer: "Para preencher e assinar um PDF grátis: abra o arquivo aqui, digite os textos necessários (nome, data, endereço) clicando onde devem ficar, depois desenhe sua assinatura — ou envie um PNG — e clique para posicionar. Baixe o PDF pronto. Tudo é processado no seu navegador, sem conta, marca d'água ou taxa.",
    intro: "Preencher e assinar PDF permite completar e assinar qualquer formulário sem imprimir. Digite nomes, datas e outros dados exatamente onde o formulário pede — em qualquer página. Depois desenhe sua assinatura com o mouse ou o dedo, ou envie um PNG transparente, e posicione onde quiser. Seu PDF, texto e assinatura são processados inteiramente no navegador.",
    steps: ["Escolha um arquivo PDF.", "Digite os textos e clique na página para posicioná-los — quantas vezes precisar.", "Desenhe sua assinatura (ou envie um PNG), posicione e baixe o PDF assinado."],
    faqs: [
      { q: "Como assinar um PDF grátis?", a: "Abra o PDF aqui, use a ferramenta de texto para preencher os campos e a de assinatura para desenhar ou enviar sua assinatura. Clique em baixar — é grátis, sem conta e sem upload." },
      { q: "A assinatura tem validade jurídica?", a: "A ferramenta adiciona uma imagem visível da assinatura, suficiente para formulários do dia a dia. Não é uma assinatura digital criptográfica (ICP-Brasil); para isso, use um serviço com certificado digital." },
      { q: "Meu documento é enviado?", a: "Não. O PDF, o texto e a assinatura nunca saem do seu dispositivo." },
    ],
  },
  "pdf-to-word": {
    name: "PDF para Word",
    description: "Converta PDF em documento Word (.docx) editável, grátis e no navegador — o arquivo não é enviado a servidor algum.",
    keywords: ["pdf para word", "converter pdf em word", "pdf para docx", "transformar pdf em word"],
    answer: "Para converter PDF em Word, carregue o arquivo e baixe o .docx gerado com o texto extraído do documento. A conversão roda no seu navegador — o PDF não é enviado.",
    intro: "PDF para Word extrai o texto do seu PDF e gera um documento .docx editável. Ideal para reaproveitar contratos, trabalhos e relatórios sem redigitar. Tudo localmente, sem upload.",
    steps: ["Escolha um PDF.", "Aguarde a extração do texto.", "Baixe o arquivo .docx."],
    faqs: [
      { q: "A formatação é mantida?", a: "O texto e a estrutura básica (parágrafos) são preservados; layouts complexos com colunas e imagens podem exigir ajustes." },
      { q: "Funciona com PDF escaneado?", a: "PDFs escaneados são imagens — use antes a ferramenta de OCR para reconhecer o texto." },
      { q: "Meu documento é enviado?", a: "Não — a conversão acontece no navegador." },
    ],
  },
  "compress-image": {
    name: "Comprimir imagem",
    description: "Comprima JPG, PNG e WebP grátis no navegador — inclusive para 20 KB, 50 KB, 100 KB ou 200 KB. Sem upload, com visualização do tamanho final.",
    keywords: ["comprimir imagem", "diminuir tamanho da foto", "comprimir foto", "reduzir imagem", "comprimir jpg", "comprimir imagem para 100kb"],
    answer: "Para comprimir uma imagem, carregue a foto, ajuste a qualidade (ou escolha um alvo como 100 KB) e baixe a versão menor. Você vê o tamanho final antes de baixar, e tudo roda no seu navegador — a foto não é enviada.",
    intro: "Comprimir imagem reduz o tamanho de fotos JPG, PNG e WebP com qualidade ajustável — ou mira um tamanho exato (20 KB, 50 KB, 100 KB, 200 KB) para formulários e cadastros com limite. Selecione várias fotos para comprimir em lote. Tudo no navegador, sem upload.",
    steps: ["Escolha uma ou várias imagens.", "Ajuste a qualidade ou escolha um tamanho-alvo.", "Baixe a imagem comprimida (ou todas em .zip)."],
    faqs: [
      { q: "Como comprimir uma foto para 100 KB?", a: "Use a predefinição de 100 KB — a ferramenta encontra automaticamente a melhor qualidade que fica abaixo do limite e mostra o tamanho final antes de baixar." },
      { q: "A foto perde qualidade?", a: "Alguma perda é inevitável ao comprimir, mas a ferramenta usa sempre a maior qualidade possível para o tamanho desejado." },
      { q: "Minhas fotos são enviadas?", a: "Não — a compressão roda inteiramente no navegador." },
    ],
  },
  "resize-image": {
    name: "Redimensionar imagem",
    description: "Redimensione fotos para dimensões exatas em pixels — Instagram, YouTube, Full HD e mais — grátis e no navegador, sem upload.",
    keywords: ["redimensionar imagem", "mudar tamanho da foto", "redimensionar foto", "alterar tamanho de imagem", "imagem 1920x1080"],
    answer: "Para redimensionar uma imagem, carregue a foto, informe a largura e a altura em pixels (ou escolha uma predefinição como Full HD ou story do Instagram) e baixe o resultado. Tudo acontece no navegador — a imagem não é enviada.",
    intro: "Redimensionar imagem altera as dimensões de uma foto para o tamanho exato que você precisa — com predefinições para redes sociais, papéis de parede e impressão. Funciona no navegador, sem upload e sem marca d'água.",
    steps: ["Escolha uma imagem.", "Digite largura e altura, ou use uma predefinição.", "Baixe a imagem redimensionada."],
    faqs: [
      { q: "A imagem fica distorcida?", a: "Se a proporção for diferente da original, sim — recorte antes na proporção certa com a ferramenta de recorte para evitar distorção." },
      { q: "Minha foto é enviada?", a: "Não — o redimensionamento usa o Canvas do navegador, localmente." },
    ],
  },
  "crop-image": {
    name: "Recortar imagem",
    description: "Recorte uma imagem ou foto online grátis: arraste a seleção sobre a área que quer manter e baixe na hora, sem perder qualidade.",
    keywords: ["recortar imagem", "cortar foto", "recortar foto", "cortar imagem online", "recortar imagem gratis"],
    answer: "Para recortar uma imagem online, carregue a foto, arraste um retângulo sobre a área que deseja manter e baixe. Não há perda de qualidade: os pixels mantidos são salvos como estão. Tudo acontece no seu navegador — a foto nunca é enviada.",
    intro: "Recortar imagem permite marcar uma área da foto e ficar só com ela: perfeito para tirar bordas, remover partes indesejadas ou melhorar o enquadramento. Funciona com JPG, PNG e WebP, é grátis, sem marca d'água e sem cadastro.",
    steps: ["Escolha uma imagem.", "Arraste sobre a prévia para marcar o recorte.", "Baixe a imagem recortada."],
    faqs: [
      { q: "Perde qualidade ao recortar?", a: "Não. O recorte apenas remove os pixels fora da seleção; os que ficam mantêm a resolução original." },
      { q: "A imagem é enviada?", a: "Não. O recorte é feito localmente com o Canvas do navegador." },
      { q: "Em que formato baixa?", a: "A imagem recortada é baixada como PNG." },
    ],
  },
  "background-remover": {
    name: "Remover fundo de imagem",
    description: "Remova o fundo de fotos grátis com IA que roda no seu navegador — sem upload, sem marca d'água, em resolução total.",
    keywords: ["remover fundo", "tirar fundo da imagem", "remover fundo de foto", "fundo transparente", "apagar fundo"],
    answer: "Para remover o fundo de uma imagem, carregue a foto e aguarde a IA separar o objeto do fundo — o resultado sai com fundo transparente (PNG), em resolução completa e sem marca d'água. O modelo roda no seu dispositivo via WebAssembly, então a foto não é enviada.",
    intro: "Remover fundo usa um modelo de IA que roda inteiramente no seu navegador para recortar pessoas, produtos e objetos com fundo transparente. Diferente de serviços como o remove.bg, sua foto nunca sai do dispositivo — e o resultado vem em resolução total, grátis.",
    steps: ["Escolha uma foto.", "Aguarde a IA processar (o modelo carrega no primeiro uso).", "Baixe o PNG com fundo transparente."],
    faqs: [
      { q: "É grátis e sem marca d'água?", a: "Sim — resolução completa, sem marca d'água e sem limites artificiais." },
      { q: "Minha foto é enviada?", a: "Não — o modelo de IA roda localmente no navegador via WebAssembly." },
      { q: "Por que o primeiro uso demora?", a: "O modelo (~40 MB) é baixado uma vez e fica em cache para os próximos usos." },
    ],
  },
  "passport-photo-maker": {
    name: "Foto 3x4 e para documentos",
    description: "Crie foto 3x4, RG, passaporte e visto online grátis: recorte no tamanho oficial e baixe com folha de impressão 10x15. Sem upload.",
    keywords: ["foto 3x4", "foto 3x4 online", "foto para passaporte", "foto para rg", "foto para documento", "criar foto 3x4 gratis"],
    answer: "Para fazer uma foto 3x4 ou de passaporte, carregue uma foto de frente, escolha o formato (3x4 brasileiro, passaporte, visto americano 5x5 etc.), ajuste o zoom e a posição do rosto e baixe a foto no tamanho exato — ou uma folha 10x15 com várias cópias para imprimir. Tudo no navegador, sem enviar sua foto.",
    intro: "Foto 3x4 e para documentos recorta sua foto nos tamanhos oficiais de documentos brasileiros e internacionais — 3x4 para RG e currículo, passaporte, vistos. Posicione o rosto, baixe a foto exata ou uma folha de impressão 10x15 com várias cópias. Tudo no seu navegador.",
    steps: ["Escolha uma foto de frente, bem iluminada.", "Selecione o formato (3x4, passaporte, visto) e ajuste zoom e posição.", "Baixe a foto ou a folha de impressão 10x15."],
    faqs: [
      { q: "Como fazer foto 3x4 pelo celular?", a: "Tire uma foto de frente contra um fundo claro, abra esta página, escolha o formato 3x4, ajuste o rosto e baixe — pronta para imprimir em qualquer gráfica ou papelaria." },
      { q: "Serve para RG, CNH e passaporte?", a: "A ferramenta gera as dimensões corretas de cada documento. Regras de fundo, expressão e iluminação são de sua responsabilidade — órgãos podem recusar fotos alteradas por IA, por isso ela apenas recorta e redimensiona." },
      { q: "Minha foto é enviada?", a: "Não — o recorte acontece localmente no navegador." },
    ],
  },
  "heic-to-jpg": {
    name: "HEIC para JPG",
    description: "Converta fotos HEIC do iPhone para JPG grátis, direto no navegador. Sem upload, sem programa — decodifique e baixe na hora.",
    keywords: ["heic para jpg", "converter heic", "foto de iphone para jpg", "abrir heic", "heic para jpeg"],
    answer: "HEIC para JPG converte o formato de fotos da Apple (usado pelos iPhones) para o JPG universal. É necessário porque muitos sites, formulários e programas do Windows não abrem HEIC. A conversão acontece inteiramente no seu navegador — a foto não é enviada.",
    intro: "iPhones salvam fotos em HEIC para economizar espaço, mas muitos sites e aplicativos não abrem esse formato. HEIC para JPG converte para o formato universal, direto no navegador.",
    steps: ["Escolha uma foto HEIC ou HEIF.", "Aguarde a decodificação (o decodificador carrega no primeiro uso).", "Baixe o JPG convertido."],
    faqs: [
      { q: "Por que a foto do iPhone não abre no Windows?", a: "Porque está em HEIC, formato que muitos programas não suportam. Converter para JPG resolve em qualquer lugar." },
      { q: "Perde qualidade?", a: "O JPG é gerado em alta qualidade (92%) — na prática a diferença é invisível." },
      { q: "Minha foto é enviada?", a: "Não — a conversão é local, no navegador." },
    ],
  },
  "image-metadata-viewer": {
    name: "Ver metadados de foto (EXIF)",
    description: "Veja os metadados EXIF ocultos de uma foto — câmera, data, configurações e localização GPS. Grátis, no navegador, sem upload.",
    keywords: ["metadados de foto", "ver exif", "dados exif", "metadados de imagem", "ver localização da foto", "exif online"],
    answer: "Para ver os metadados de uma foto, abra a imagem aqui — todos os campos EXIF aparecem na hora: câmera, lente, data e hora, configurações e coordenadas GPS (com link para o mapa) se a foto estiver geolocalizada. A leitura é local, como um ExifTool no navegador — nada é enviado.",
    intro: "Ver metadados de foto revela os dados EXIF escondidos nas suas imagens — câmera, data, configurações e até coordenadas GPS — para você saber exatamente o que um arquivo revela antes de compartilhar. Tudo lido localmente no navegador.",
    steps: ["Escolha uma imagem JPEG, PNG, TIFF ou HEIC.", "Revise todos os metadados encontrados.", "Verifique se há localização GPS que você queira remover antes de compartilhar."],
    faqs: [
      { q: "Dá para ver onde a foto foi tirada?", a: "Sim — se a foto tiver coordenadas GPS gravadas, elas aparecem com link para o mapa. Use o removedor de metadados para apagá-las antes de compartilhar." },
      { q: "Por que minha foto não tem metadados?", a: "WhatsApp, Instagram e a maioria dos apps de mensagem removem os EXIF no envio; capturas de tela também não têm dados de câmera." },
      { q: "Minha foto é enviada?", a: "Não — os metadados são lidos localmente." },
    ],
  },
  "video-to-gif": {
    name: "Vídeo para GIF",
    description: "Transforme um trecho de vídeo em GIF animado — grátis, no navegador. Escolha duração, fps e tamanho. Sem upload.",
    keywords: ["video para gif", "mp4 para gif", "transformar video em gif", "criar gif de video", "fazer gif"],
    answer: "Para transformar um vídeo em GIF, carregue o arquivo, escolha o trecho (início e duração), ajuste fps e largura e clique em gerar. O GIF é renderizado com paleta otimizada, tudo via FFmpeg no seu navegador — nada é enviado. Mantenha o trecho curto para o GIF ficar leve.",
    intro: "Vídeo para GIF converte um trecho curto de vídeo em um GIF animado para compartilhar. Escolha o segmento, a taxa de quadros e o tamanho — tudo roda no navegador via ffmpeg.wasm, sem upload, sem marca d'água.",
    steps: ["Escolha um arquivo de vídeo.", "Defina início, duração, fps e largura.", "Clique em gerar e baixe o GIF."],
    faqs: [
      { q: "Como transformar um vídeo em GIF?", a: "Carregue o vídeo aqui, escolha os segundos que quer converter e clique em gerar — o GIF baixa direto no seu dispositivo, grátis e sem marca d'água." },
      { q: "O GIF pode ter som?", a: "Não — o formato GIF não tem áudio. Se precisar de som, corte o trecho como vídeo com a ferramenta de cortar vídeo." },
      { q: "Meu vídeo é enviado?", a: "Não — a conversão roda localmente via ffmpeg.wasm." },
    ],
  },
  "qr-code-generator": {
    name: "Gerador de QR Code",
    description: "Crie QR Codes grátis para links, texto, Wi-Fi e PIX-copia-e-cola — com cores e logo. Baixe em PNG ou SVG. Sem cadastro, no navegador.",
    keywords: ["gerador de qr code", "criar qr code", "qr code gratis", "fazer qr code", "qr code de link"],
    answer: "Para criar um QR Code, digite o link ou texto, personalize cores e tamanho e baixe em PNG ou SVG. O código é gerado inteiramente no seu navegador — o conteúdo não é enviado a servidor algum e o QR não expira.",
    intro: "Gerador de QR Code cria códigos para links, textos, Wi-Fi e mais, com personalização de cor e download em PNG ou SVG. Gerado localmente: seu conteúdo não é enviado e o código nunca expira.",
    steps: ["Digite o link ou texto.", "Personalize cor e tamanho.", "Baixe em PNG ou SVG."],
    faqs: [
      { q: "O QR Code expira?", a: "Não — o código é estático e aponta direto para o seu conteúdo; funciona para sempre." },
      { q: "Posso usar comercialmente?", a: "Sim, sem restrições e sem custo." },
      { q: "Meu conteúdo é enviado?", a: "Não — o QR é gerado localmente no navegador." },
    ],
  },
  "word-counter": {
    name: "Contador de palavras",
    description: "Conte palavras, caracteres, frases e parágrafos em tempo real enquanto digita — grátis, no navegador, nada é enviado.",
    keywords: ["contador de palavras", "contar palavras", "quantas palavras", "contador de caracteres e palavras"],
    answer: "Para contar palavras, cole ou digite o texto e veja em tempo real o número de palavras, caracteres, frases e parágrafos, além do tempo estimado de leitura. Tudo acontece no seu navegador.",
    intro: "Contador de palavras mostra em tempo real palavras, caracteres, frases e parágrafos do seu texto. Útil para redações, trabalhos acadêmicos, posts e limites de caracteres.",
    steps: ["Cole ou digite o texto.", "Veja a contagem atualizar em tempo real.", "Confira também frases, parágrafos e tempo de leitura."],
    faqs: [
      { q: "Meu texto é enviado?", a: "Não — a contagem roda inteiramente no navegador." },
      { q: "Tem limite de tamanho?", a: "Não — textos longos funcionam normalmente." },
    ],
  },
  "character-counter": {
    name: "Contador de caracteres",
    description: "Conte caracteres com e sem espaços em tempo real — para Instagram, X/Twitter, SMS e formulários. Grátis e no navegador.",
    keywords: ["contador de caracteres", "contar caracteres", "caracteres com espaço", "limite de caracteres"],
    answer: "Para contar caracteres, cole o texto e veja na hora o total com e sem espaços, além de palavras e linhas — útil para limites de redes sociais e formulários. Nada é enviado.",
    intro: "Contador de caracteres mostra o total de caracteres (com e sem espaços), palavras e linhas do seu texto em tempo real — perfeito para bios, legendas e campos com limite.",
    steps: ["Cole ou digite o texto.", "Veja o total de caracteres com e sem espaços.", "Ajuste o texto até caber no limite."],
    faqs: [
      { q: "Espaços contam como caracteres?", a: "Na maioria dos limites (redes sociais, formulários), sim — por isso mostramos as duas contagens." },
      { q: "Meu texto é enviado?", a: "Não — tudo roda no navegador." },
    ],
  },
  "case-converter": {
    name: "Conversor de maiúsculas e minúsculas",
    description: "Converta texto para MAIÚSCULAS, minúsculas, Título ou Frase em um clique — grátis, instantâneo e no navegador.",
    keywords: ["maiusculas para minusculas", "converter para maiusculas", "letra maiuscula", "conversor de letras"],
    answer: "Para converter maiúsculas e minúsculas, cole o texto e escolha o formato: MAIÚSCULAS, minúsculas, Formato De Título ou Formato de frase. A conversão é instantânea e acontece no seu navegador.",
    intro: "Conversor de maiúsculas e minúsculas transforma o texto entre MAIÚSCULAS, minúsculas, Título e Frase — útil para corrigir textos digitados com Caps Lock ou padronizar títulos.",
    steps: ["Cole o texto.", "Escolha o formato desejado.", "Copie o resultado com um clique."],
    faqs: [
      { q: "Tem limite de tamanho?", a: "Não — a conversão é local e instantânea mesmo em textos longos." },
      { q: "Meu texto é enviado?", a: "Não — nada sai do seu dispositivo." },
    ],
  },
  "text-summarizer": {
    name: "Resumidor de texto",
    description: "Resuma textos automaticamente destacando as frases mais importantes — grátis, no navegador, sem enviar seu texto.",
    keywords: ["resumir texto", "resumidor de texto", "resumo automatico", "resumir texto online"],
    answer: "Para resumir um texto, cole o conteúdo e escolha o tamanho do resumo — as frases mais representativas são selecionadas por análise de frequência, localmente no seu navegador. Nada é enviado.",
    intro: "Resumidor de texto extrai as frases mais importantes de um artigo ou documento usando análise de frequência de termos — um resumo rápido, gerado inteiramente no seu navegador.",
    steps: ["Cole o texto.", "Escolha o tamanho do resumo.", "Copie o resultado."],
    faqs: [
      { q: "É um resumo feito por IA?", a: "É um resumo extrativo (seleciona as frases mais relevantes do próprio texto), não uma reescrita por IA — rápido, previsível e 100% local." },
      { q: "Meu texto é enviado?", a: "Não — a análise roda no navegador." },
    ],
  },
  "compound-interest-calculator": {
    name: "Calculadora de juros compostos",
    description: "Calcule juros compostos com aportes mensais: veja o montante final, os juros ganhos e a evolução mês a mês. Grátis e no navegador.",
    keywords: ["calculadora de juros compostos", "juros compostos", "calcular juros compostos", "simulador de juros compostos", "juros sobre juros"],
    answer: "Para calcular juros compostos, informe o valor inicial, o aporte mensal, a taxa de juros e o prazo — a calculadora mostra o montante final, quanto veio de juros e a evolução período a período. Tudo calculado no seu navegador.",
    intro: "Calculadora de juros compostos simula o crescimento de um investimento com valor inicial, aportes mensais, taxa e prazo — mostrando o efeito dos juros sobre juros na sua reserva. Os cálculos rodam localmente, sem enviar seus dados.",
    steps: ["Informe o valor inicial e o aporte mensal.", "Defina a taxa de juros (mensal ou anual) e o prazo.", "Veja o montante final, os juros ganhos e a evolução."],
    faqs: [
      { q: "Qual a fórmula dos juros compostos?", a: "M = C × (1 + i)^t — o montante cresce exponencialmente porque os juros de cada período passam a render também. Com aportes mensais, cada depósito entra na conta a partir do mês seguinte." },
      { q: "A taxa é mensal ou anual?", a: "Você escolhe — a calculadora converte automaticamente entre as duas." },
      { q: "Meus dados são salvos?", a: "Não — o cálculo é local e nada é enviado ou armazenado." },
    ],
  },
  "percentage-calculator": {
    name: "Calculadora de porcentagem",
    description: "Calcule porcentagens de todas as formas: X% de um valor, variação percentual, proporções e mais. Grátis, instantânea, no navegador.",
    keywords: ["calculadora de porcentagem", "calcular porcentagem", "porcentagem de um valor", "como calcular porcentagem", "variação percentual"],
    answer: "Para calcular porcentagem, escolha o tipo de conta — quanto é X% de Y, que porcentagem X é de Y, ou a variação percentual entre dois valores — preencha os campos e veja o resultado na hora. Tudo no navegador.",
    intro: "Calculadora de porcentagem resolve as contas percentuais do dia a dia: desconto, aumento, proporção e variação entre dois valores — com resultado instantâneo enquanto você digita.",
    steps: ["Escolha o tipo de cálculo.", "Preencha os valores.", "Veja o resultado na hora."],
    faqs: [
      { q: "Como calcular X% de um valor?", a: "Multiplique o valor por X e divida por 100 — ou preencha os dois campos aqui e veja o resultado pronto." },
      { q: "Como calcular variação percentual?", a: "((valor final − valor inicial) ÷ valor inicial) × 100. A calculadora faz isso automaticamente no modo variação." },
    ],
  },
  "discount-calculator": {
    name: "Calculadora de desconto",
    description: "Calcule o preço final com desconto e quanto você economiza — inclusive descontos acumulados. Grátis e no navegador.",
    keywords: ["calculadora de desconto", "calcular desconto", "porcentagem de desconto", "preço com desconto"],
    answer: "Para calcular um desconto, informe o preço original e a porcentagem — a calculadora mostra o preço final e a economia. Também aceita cupom adicional sobre o valor já com desconto. Tudo no navegador.",
    intro: "Calculadora de desconto mostra o preço final e a economia de qualquer promoção, incluindo descontos acumulados (desconto sobre desconto) — na hora, enquanto você digita.",
    steps: ["Informe o preço original.", "Digite a porcentagem de desconto (e um cupom extra, se houver).", "Veja o preço final e quanto você economiza."],
    faqs: [
      { q: "Como calcular 20% de desconto?", a: "Multiplique o preço por 0,80 — ou digite o preço e 20% aqui e veja o valor final pronto." },
      { q: "Desconto sobre desconto soma?", a: "Não — 20% + 10% não são 30%: o segundo desconto incide sobre o preço já reduzido. A calculadora considera isso." },
    ],
  },
  "age-calculator": {
    name: "Calculadora de idade",
    description: "Calcule a idade exata em anos, meses e dias a partir da data de nascimento — e quanto falta para o próximo aniversário. Grátis.",
    keywords: ["calculadora de idade", "calcular idade", "idade exata", "quantos anos tenho"],
    answer: "Para calcular a idade, informe a data de nascimento — o resultado mostra a idade exata em anos, meses e dias, o total de dias vividos e quanto falta para o próximo aniversário. Tudo no navegador.",
    intro: "Calculadora de idade mostra a idade exata em anos, meses e dias entre a data de nascimento e hoje (ou qualquer outra data) — com contagem regressiva para o próximo aniversário.",
    steps: ["Informe a data de nascimento.", "Opcionalmente, mude a data de referência.", "Veja a idade exata e o próximo aniversário."],
    faqs: [
      { q: "Considera anos bissextos?", a: "Sim — o cálculo usa o calendário real, incluindo 29 de fevereiro." },
      { q: "Meus dados são salvos?", a: "Não — o cálculo é local e nada é armazenado." },
    ],
  },
  "unit-converter": {
    name: "Conversor de medidas",
    description: "Converta comprimento, peso, temperatura, volume e mais — metros, pés, quilos, libras, litros. Grátis e instantâneo.",
    keywords: ["conversor de medidas", "converter unidades", "metros para pes", "quilos para libras", "conversor de unidades"],
    answer: "Para converter medidas, escolha a categoria (comprimento, peso, temperatura, volume…), informe o valor e veja a conversão instantânea entre as unidades. Tudo roda no navegador.",
    intro: "Conversor de medidas transforma valores entre unidades métricas e imperiais — comprimento, peso, temperatura, volume, área e velocidade — com resultado enquanto você digita.",
    steps: ["Escolha a categoria e as unidades.", "Digite o valor.", "Veja a conversão na hora."],
    faqs: [
      { q: "Quais unidades estão disponíveis?", a: "As mais usadas de cada categoria: metros/pés/polegadas, kg/libras, Celsius/Fahrenheit, litros/galões e mais." },
    ],
  },
  "password-generator": {
    name: "Gerador de senhas",
    description: "Gere senhas fortes e aleatórias com o tamanho e os caracteres que você escolher — criptograficamente seguras, geradas no seu navegador.",
    keywords: ["gerador de senhas", "criar senha forte", "senha aleatoria", "gerar senha segura"],
    answer: "Para gerar uma senha forte, escolha o tamanho e os tipos de caracteres (maiúsculas, números, símbolos) e copie o resultado. As senhas são geradas com a API Web Crypto do navegador — aleatoriedade criptográfica, sem nada enviado ou salvo.",
    intro: "Gerador de senhas cria senhas fortes e aleatórias com aleatoriedade criptográfica (Web Crypto API), no tamanho e composição que você escolher. Geradas localmente: nenhuma senha é enviada ou armazenada.",
    steps: ["Escolha o tamanho da senha.", "Marque os tipos de caracteres.", "Gere e copie a senha."],
    faqs: [
      { q: "A senha é realmente aleatória?", a: "Sim — usa a Web Crypto API do navegador, a mesma fonte de aleatoriedade usada em criptografia." },
      { q: "A senha é enviada ou salva?", a: "Não — ela existe só na sua tela até você copiá-la." },
    ],
  },
  "signature-generator": {
    name: "Criar assinatura digital",
    description: "Desenhe ou digite sua assinatura e baixe em PNG com fundo transparente — grátis, no navegador, para assinar documentos.",
    keywords: ["criar assinatura", "assinatura digital", "desenhar assinatura", "gerador de assinatura", "assinatura png"],
    answer: "Para criar uma assinatura digital, desenhe com o mouse ou o dedo — ou digite seu nome e escolha uma fonte de assinatura — e baixe o PNG com fundo transparente, pronto para inserir em PDFs e documentos. Tudo criado no seu navegador.",
    intro: "Criar assinatura digital gera sua assinatura desenhada ou digitada em PNG transparente, para usar em PDFs, e-mails e documentos. Nada é enviado: a assinatura nunca sai do seu dispositivo.",
    steps: ["Escolha entre desenhar ou digitar.", "Desenhe a assinatura ou escolha um estilo de fonte.", "Baixe o PNG transparente."],
    faqs: [
      { q: "O PNG tem fundo transparente?", a: "Sim — encaixa limpo sobre qualquer documento." },
      { q: "Minha assinatura é enviada?", a: "Não — é criada inteiramente no navegador." },
    ],
  },
};
