"use client";

import { useEffect, useState } from "react";

const GENERATORS = [
  "stable diffusion", "automatic1111", "comfyui", "invokeai", "sdxl", "midjourney",
  "dall-e", "dall·e", "dalle", "openai", "adobe firefly", "firefly", "novelai",
  "leonardo.ai", "leonardo", "stability.ai", "bing image creator", "ideogram",
  "playground ai", "craiyon", "nightcafe", "getimg", "flux.1", "generated by ai", "made with ai",
];

interface Result {
  level: "ai" | "credentials" | "none";
  signals: string[];
  prompt: string | null;
}

function isPng(b: Uint8Array) {
  return b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47;
}

// Parse uncompressed PNG tEXt/iTXt chunks → keyword/value pairs (stop at image data).
function pngTextChunks(b: Uint8Array): Record<string, string> {
  const out: Record<string, string> = {};
  let p = 8;
  const dv = new DataView(b.buffer);
  const dec = new TextDecoder("latin1");
  while (p + 8 <= b.length) {
    const len = dv.getUint32(p);
    const type = dec.decode(b.subarray(p + 4, p + 8));
    const data = b.subarray(p + 8, p + 8 + len);
    if (type === "IDAT" || type === "IEND") break;
    if (type === "tEXt") {
      const z = data.indexOf(0);
      if (z > 0) out[dec.decode(data.subarray(0, z))] = dec.decode(data.subarray(z + 1));
    } else if (type === "iTXt") {
      const z = data.indexOf(0);
      if (z > 0) {
        // keyword \0 compFlag compMethod \0 langTag \0 transKeyword \0 text
        let q = z + 3;
        q = data.indexOf(0, q) + 1;
        q = data.indexOf(0, q) + 1;
        out[dec.decode(data.subarray(0, z))] = dec.decode(data.subarray(q));
      }
    }
    p += 12 + len;
  }
  return out;
}

export default function AiImageChecker({ initialFiles }: { initialFiles?: File[] }) {
  const [preview, setPreview] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<Result | null>(null);

  useEffect(() => {
    const f = initialFiles?.find((x) => x.type.startsWith("image/"));
    if (f) run(f);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialFiles]);

  function onFile(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0];
    if (f) run(f);
  }

  async function run(file: File) {
    setPreview(URL.createObjectURL(file));
    setBusy(true);
    setResult(null);
    try {
      const buf = new Uint8Array(await file.arrayBuffer());
      const signals: string[] = [];
      let prompt: string | null = null;
      let textBlob = "";

      if (isPng(buf)) {
        const chunks = pngTextChunks(buf);
        for (const [k, v] of Object.entries(chunks)) {
          textBlob += " " + k + " " + v;
          if (/^(parameters|prompt|workflow|sd-metadata|comment|dream)$/i.test(k) && v.length > 5) {
            prompt = v.slice(0, 1500);
            signals.push(`Embedded generation data in PNG “${k}” field`);
          }
        }
      }

      // EXIF / XMP software + comments.
      try {
        const exifr = (await import("exifr")).default;
        const data = await exifr.parse(file, true).catch(() => null);
        if (data) {
          textBlob += " " + [data.Software, data.UserComment, data.ImageDescription, data.Creator, data.CreatorTool, data.Description].filter(Boolean).join(" ");
        }
      } catch { /* ignore */ }

      // Byte scan (first 3 MB) for Content Credentials + generator names.
      const scan = new TextDecoder("latin1").decode(buf.subarray(0, 3_000_000)).toLowerCase();
      const hay = (textBlob + " " + scan).toLowerCase();

      const hasC2pa = scan.includes("c2pa") || scan.includes("jumbf") || scan.includes("contentcred") || scan.includes("content credentials");
      if (hasC2pa) signals.push("Content Credentials (C2PA) provenance manifest found");

      const gens = GENERATORS.filter((g) => hay.includes(g));
      for (const g of gens) signals.push(`Generator signature: “${g}”`);

      let level: Result["level"] = "none";
      if (prompt || gens.length) level = "ai";
      else if (hasC2pa) level = "credentials";

      setResult({ level, signals: [...new Set(signals)], prompt });
    } catch {
      setResult({ level: "none", signals: [], prompt: null });
    } finally {
      setBusy(false);
    }
  }

  const verdict = result && {
    ai: { text: "Likely AI-generated", color: "#ff6b6b", note: "AI signatures were found in this image's metadata." },
    credentials: { text: "Has Content Credentials", color: "#ffce5c", note: "This image carries C2PA provenance data — open it in a Content Credentials viewer to see who/what made it." },
    none: { text: "No AI signals found — inconclusive", color: "var(--muted)", note: "No AI metadata was detected. This does NOT prove it's human-made — metadata may have been stripped (e.g. a screenshot). Pixel-level detection would require an ML model." },
  }[result.level];

  return (
    <div>
      <div className="field">
        <label>Choose an image</label>
        <input type="file" accept="image/*" onChange={onFile} className="input" disabled={busy} />
      </div>

      {/* eslint-disable-next-line @next/next/no-img-element */}
      {preview && <img src={preview} alt="preview" className="preview-img" style={{ maxHeight: 220 }} />}
      {busy && <p style={{ color: "var(--muted)", marginTop: 10 }}>Inspecting metadata…</p>}

      {result && verdict && (
        <>
          <div className="stat" style={{ borderTop: `3px solid ${verdict.color}`, marginTop: 12 }}>
            <div className="n" style={{ fontSize: "1.3rem", color: verdict.color }}>{verdict.text}</div>
            <div className="l">{verdict.note}</div>
          </div>
          {result.signals.length > 0 && (
            <ul className="file-list" style={{ marginTop: 12 }}>
              {result.signals.map((s, i) => <li key={i}>✓ {s}</li>)}
            </ul>
          )}
          {result.prompt && (
            <div className="field" style={{ marginTop: 12 }}>
              <label>Embedded generation prompt / parameters</label>
              <textarea readOnly value={result.prompt} className="mono" style={{ minHeight: 120 }} />
            </div>
          )}
        </>
      )}

      <div style={{ background: "var(--accent-soft, rgba(124,140,255,.14))", border: "1px solid var(--border)", borderRadius: 10, padding: "12px 14px", marginTop: 16, fontSize: ".85rem", color: "var(--muted)" }}>
        ℹ️ This checks <strong style={{ color: "var(--text)" }}>metadata and Content Credentials</strong>, not pixels. It reliably flags AI images that still carry their metadata, but can&apos;t judge images whose metadata was removed.
      </div>
      <p className="privacy-note">🔒 The file is read in your browser — your image is never uploaded.</p>
    </div>
  );
}
